-- PhD Admission Portal — new workflow columns.
-- Run this in the Supabase SQL Editor before using the updated Research Dept.
--
-- New PhD pipeline:
--   Student entry (Application No)
--     -> Document Dept verify        -> research_forwarded_at
--     -> Research Dept               -> offer/entrance letters (Active/Inactive)
--     -> forward to Exam Section     -> exam_forwarded_at + enrollment_no
--     -> Exam Section                -> admit card, result (result_released_at)

-- 13. Stream (research stream / area of the Ph.D candidate).
ALTER TABLE students ADD COLUMN IF NOT EXISTS stream TEXT;

-- 3. Set when the Document Dept forwards a verified Ph.D student to Research.
ALTER TABLE students ADD COLUMN IF NOT EXISTS research_forwarded_at TIMESTAMPTZ;

-- 4/5. Active = the letter is published, so the Centre & Student panels show a
-- Download button for it. Inactive = generated by admin only, not visible.
ALTER TABLE students ADD COLUMN IF NOT EXISTS offer_letter_active BOOLEAN DEFAULT FALSE;
ALTER TABLE students ADD COLUMN IF NOT EXISTS entrance_letter_active BOOLEAN DEFAULT FALSE;

-- 8. Set by the "Send Result" button in the Exam Section; until then the
-- declared result stays hidden from the student portal.
ALTER TABLE students ADD COLUMN IF NOT EXISTS result_released_at TIMESTAMPTZ;

-- Speeds up the Research Dept queue.
CREATE INDEX IF NOT EXISTS idx_students_research_forwarded
  ON students (research_forwarded_at)
  WHERE research_forwarded_at IS NOT NULL;
