-- ============================================================
-- Commission on the fee a centre pays to be set up
-- ------------------------------------------------------------
-- A super centre earns on the money its centres put in. Recharges were
-- covered; the fee a centre pays at REGISTRATION was not, even though it is
-- the first money that centre ever hands over. It never became a
-- recharge_requests row — it is taken as an admission coupon, not a wallet
-- top-up — so the Center Recharges tab had nothing to show and nothing to
-- generate against.
--
-- The rate is the same one recharges use: center_commissions.percent, set per
-- (centre, super centre). No second rate to keep in step.
--
-- Nothing is generated by running this. Every existing centre simply becomes a
-- row the admin can Generate against, exactly like a recharge, and the money
-- still only moves on Activate.
--
-- Run once in Supabase -> SQL Editor. Safe to re-run.
-- Depends on: add_commission_recipients.sql, add_commission_payout.sql.
-- ============================================================

-- ── 1. Let a commission row stand for something other than a recharge ──
-- recharge_id was NOT NULL, which is what made this impossible.
ALTER TABLE recharge_commissions ALTER COLUMN recharge_id DROP NOT NULL;
ALTER TABLE recharge_commissions ADD COLUMN IF NOT EXISTS center_id uuid REFERENCES centers(id) ON DELETE CASCADE;
ALTER TABLE recharge_commissions ADD COLUMN IF NOT EXISTS source text NOT NULL DEFAULT 'recharge';

COMMENT ON COLUMN recharge_commissions.source IS
  'recharge = earned on a recharge_requests row; registration = earned on the fee the centre paid to be created.';
COMMENT ON COLUMN recharge_commissions.center_id IS
  'The centre the commission was earned ON. Only set for source = registration, where there is no recharge to read it from.';

-- The existing UNIQUE (recharge_id, super_center_id) stops a recharge being
-- paid twice, but treats NULLs as distinct — so it does not constrain
-- registration rows at all. This does, and only for them.
CREATE UNIQUE INDEX IF NOT EXISTS recharge_commissions_one_registration
  ON recharge_commissions (center_id, super_center_id)
  WHERE source = 'registration';

-- ── 2. Mint the registration commission for one centre ──
-- Mirrors generate_commission_payables: records what is OWED, pays nothing.
-- commission_set_sent then moves it into the wallet, unchanged — it reads a
-- recharge_commissions row by id and does not care what the row stands for.
CREATE OR REPLACE FUNCTION generate_registration_commission(p_center uuid)
RETURNS TABLE (super_center_id uuid, super_center_name text, amount numeric, percent numeric)
LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path = public AS $$
DECLARE
  c      record;
  rec    record;
  v_amt  numeric;
  v_made int := 0;
BEGIN
  IF NOT is_admin() THEN
    RAISE EXCEPTION 'Only the university admin can generate commission.';
  END IF;

  -- Locked before reading, so two clicks cannot both get past the "already
  -- paid?" test below.
  SELECT ctr.id, ctr.center_name, ctr.amount_paid INTO c
    FROM centers ctr WHERE ctr.id = p_center FOR UPDATE;

  IF c.id IS NULL THEN
    RAISE EXCEPTION 'Centre not found.';
  END IF;
  IF COALESCE(c.amount_paid, 0) <= 0 THEN
    RAISE EXCEPTION 'No registration fee is recorded for this centre.';
  END IF;

  FOR rec IN
    SELECT cc.super_center_id AS sc_id, cc.percent AS pct, s.center_name AS sc_name
      FROM center_commissions cc
      JOIN centers s ON s.id = cc.super_center_id
     WHERE cc.center_id = c.id
       AND NOT EXISTS (
         SELECT 1 FROM recharge_commissions rc
          WHERE rc.source = 'registration'
            AND rc.center_id = c.id
            AND rc.super_center_id = cc.super_center_id
       )
     ORDER BY s.center_name
  LOOP
    v_amt := round(c.amount_paid * rec.pct / 100.0);
    -- A rate so small it rounds to nothing is skipped rather than failing the
    -- whole run; the other recipients still get paid.
    CONTINUE WHEN v_amt < 1;

    INSERT INTO recharge_commissions (recharge_id, center_id, source, super_center_id, percent, amount)
    VALUES (NULL, c.id, 'registration', rec.sc_id, rec.pct, v_amt);

    -- base_fee is NOT NULL and has no meaning here, so it records 0;
    -- charged_amount carries the registration fee it was worked out on.
    INSERT INTO commission_ledger (super_center_id, center_id, amount, base_fee, charged_amount, kind, note)
    VALUES (rec.sc_id, c.id, v_amt, 0, c.amount_paid, 'registration',
            format('%s%% commission on centre registration fee', rec.pct));

    v_made := v_made + 1;

    super_center_id   := rec.sc_id;
    super_center_name := rec.sc_name;
    amount            := v_amt;
    percent           := rec.pct;
    RETURN NEXT;
  END LOOP;

  IF v_made = 0 THEN
    RAISE EXCEPTION 'Nothing to generate: this centre has no commission recipients left to pay for its registration.';
  END IF;
END $$;

REVOKE ALL ON FUNCTION generate_registration_commission(uuid) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION generate_registration_commission(uuid) TO authenticated;

SELECT 'registration commission ready' AS result,
       (SELECT count(*) FROM centers WHERE COALESCE(amount_paid, 0) > 0) AS centres_with_a_registration_fee,
       (SELECT count(*) FROM recharge_commissions WHERE source = 'registration') AS already_generated;
